piVersion: v1
kind: Service
metadata:
  name: cassandra-expose
  labels:
    app: cassandra-expose
spec:
  type: LoadBalancer
  selector:
    app: cassandra
  ports:
    - port: 7000
      name: intra-node
    - port: 7001
      name: tls-intra-node
    - port: 7199
      name: jmx
    - port: 9042
      name: cql
